version: '3.8'

services:
  catalog-service:
    build:
      context: .
      dockerfile: src/poc/CatalogService/Dockerfile
    ports:
      - "9001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - ./data/catalog:/app/data
    networks:
      - reliablestore-network
    restart: unless-stopped

  customer-service:
    build:
      context: .
      dockerfile: src/poc/CustomerService/Dockerfile
    ports:
      - "9002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - ./data/customer:/app/data
    networks:
      - reliablestore-network
    restart: unless-stopped

  order-service:
    build:
      context: .
      dockerfile: src/poc/OrderService/Dockerfile
    ports:
      - "9003:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - ./data/order:/app/data
      - ./data/shared:/app/shared  # Shared data for cross-service coordination
    networks:
      - reliablestore-network
    depends_on:
      - catalog-service
      - customer-service
      - payment-service
      - shipping-service
    restart: unless-stopped

  payment-service:
    build:
      context: .
      dockerfile: src/poc/PaymentService/Dockerfile
    ports:
      - "9004:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - ./data/payment:/app/data
    networks:
      - reliablestore-network
    restart: unless-stopped

  shipping-service:
    build:
      context: .
      dockerfile: src/poc/ShippingService/Dockerfile
    ports:
      - "9005:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - ./data/shipping:/app/data
    networks:
      - reliablestore-network
    restart: unless-stopped

networks:
  reliablestore-network:
    driver: bridge

volumes:
  catalog-data:
  customer-data:
  order-data:
  payment-data:
  shipping-data:
  shared-data: