version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: reliablestore-sqlserver-tests
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD:-YourStrong@Passw0rd}
      - MSSQL_PID=Developer
      - MSSQL_IP_ADDRESS=0.0.0.0
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    healthcheck:
      test: [
        "CMD-SHELL",
        "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"${SA_PASSWORD:-YourStrong@Passw0rd}\" -C -Q \"SELECT 1\" > /dev/null"
      ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - reliablestore-test

  init-db:
    image: mcr.microsoft.com/mssql/server:2022-latest  # Use same image
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
      SA_PASSWORD: ${SA_PASSWORD:-YourStrong@Passw0rd}
    entrypoint: >
      bash -c "
        echo 'Waiting for SQL Server to be ready…';
        until /opt/mssql-tools18/bin/sqlcmd -S sqlserver -U sa -P \"$$SA_PASSWORD\" -C -Q 'SELECT 1' &>/dev/null; do
          echo 'Still waiting...';
          sleep 2;
        done;
        echo 'Creating ReliableStoreTest if it does not exist…';
        /opt/mssql-tools18/bin/sqlcmd -S sqlserver -U sa -P \"$$SA_PASSWORD\" -C -Q \"IF DB_ID(N'ReliableStoreTest') IS NULL CREATE DATABASE [ReliableStoreTest];\";
        echo 'Database creation complete.';
      "
    restart: "no"
    networks:
      - reliablestore-test

networks:
  reliablestore-test:
    driver: bridge

volumes:
  sqlserver-data:
    driver: local